### ISSUE TITLE
game not loading after patches

### ISSUE THREAD

**Issue by pokeheadroom** [vStar925/RDR1-Keyboard-Mouse#2]
not quite sure what could've caused it as i feel like i did everything i was supposed to do... although i guess i could always be wrong.

after i replaced the files in MagicRDR i saved the .rpf file, it then asked me about the write order and if i wanted to save entries by offset which i said yes to.

i then opened up wx360, loaded up the iso and right clicked/replace rdr2_layer0.rpf and closed the tool.
upon loading my game i was met with a black screen which is where i am at right now.

Edit: i realized at no point i was instructed to use the iso as the main method of running the game. running from the default .xex has fixed this issue.

rewasd isnt working but thats a rewasd issue

**Comment by vStar925** [comment]
Try to run the unmodified iso if you still have it. If it works go ahead and extract it all again with wx360 and swap the files in rdr2_layer0.rpf again. The way you did it sounds exactly like it was in the guide so something must have just went wrong.

One thing I can think of is after saving in MagicRDR and it says it's done, give it a few seconds. It becomes unresponsive but as soon as it responds, you're free to close it. You also don't need to repack it into an iso, you can just leave the files loose and run the xex (that's how I have it)

**Comment by vStar925** [comment]
Try to run the unmodified iso if you still have it. If it works go ahead and extract it all again with wx360 and swap the files in rdr2_layer0.rpf again. The way you did it sounds exactly like it was in the guide so something must have just went wrong.

One thing I can think of is after saving in MagicRDR and it says it's done, give it a few seconds. It becomes unresponsive but as soon as it responds, you're free to close it. You also don't need to repack it into an iso, you can just leave the files loose and run the xex (that's how I have it)

**Comment by pokeheadroom** [comment]
i just figured it out as you replied and edited the issue as such, thanks for the heads-up though. rewasd isnt working for me but im convinced its rewasd in general since neither fortnite or valorant are working for me.

this second time arround i did actually give it some time before closing rdrmagic so you were likely correct in assuming that i just closed the tool too fast after saving

**Comment by vStar925** [comment]
For the rewasd issue, you have to setup and group your mouse and keyboard first I believe. I walked through this process with someone else earlier and the simplest way to do it is click the radar dish icon in the bottom left

Edit: cause I accidentally closed again

Click your mouse and keyboard so they light up on the left, that way you know which one to use. Right click either one and group it with the other. Then make that group active
