### ISSUE TITLE
rb and lb button images in inventory are not changed

### ISSUE THREAD

**Issue by MrSujanofan** [vStar925/RDR1-Keyboard-Mouse#4]
![Ca22222pture](https://github.com/vStar925/RDR1-Keyboard-Mouse/assets/105348153/9d347050-5442-471e-b3f5-21d8e9cfe12a)

**Comment by vStar925** [comment]
Yeah I was waiting to see if the buttons were used anywhere else before I swapped them out. Until then, you can use

NUM7/NUM9 (all configs)
Q/Tab (Tab as Weapon Wheel Config )
Q (All other configs)

**Comment by MrSujanofan** [comment]
the button images are in satchel.xsf btw if your gonna update

**Comment by vStar925** [comment]
Adding it in the next update.

![image](https://github.com/vStar925/RDR1-Keyboard-Mouse/assets/100389738/a416e9e9-7d88-4c78-8e51-2f6a6e305f5b)
