### ISSUE TITLE
Change ReWASD to X360ce v4

### ISSUE THREAD

**Issue by Skynet19972029** [vStar925/RDR1-Keyboard-Mouse#7]
X360ce V4 allows for a fake XBOX 360 controller and you can map keyboard and mouse in it.

I am doing the profile right now for testing.

The only issue i found so far, is not being able to bind 2 keyboard/mouse keys to the same button.
Like B, I can't find a way to bind it to Numpad 0 and R
But, i might be missing something perhaps?

https://youtu.be/XzY5OuezPTE

Software can be downloaded from here.
https://www.x360ce.com

**Comment by Bartek16194** [comment]
Please share the profile and short instructions when you're done

**Comment by vStar925** [comment]
This is not an issue, this is just an advertisement.
